// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqZ_pZ8_y-4R0gpyQrR93XazG3jz0MF8w',
    appId: '1:520533736138:web:2144430b2366745e801233',
    messagingSenderId: '520533736138',
    projectId: 'android-main-activity',
    authDomain: 'android-main-activity.firebaseapp.com',
    storageBucket: 'android-main-activity.firebasestorage.app',
    measurementId: 'G-B8M4EQPJG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-qUHP-2ks5OIKHcZqB_vy3lCg5LrgGPk',
    appId: '1:520533736138:android:cdb53eab1a8086b7801233',
    messagingSenderId: '520533736138',
    projectId: 'android-main-activity',
    storageBucket: 'android-main-activity.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIoKe9PbJOQyBNjYonemRg39trAYdNsX8',
    appId: '1:520533736138:ios:e4b4b87f38c619d0801233',
    messagingSenderId: '520533736138',
    projectId: 'android-main-activity',
    storageBucket: 'android-main-activity.firebasestorage.app',
    androidClientId: '520533736138-jen63e63sj6fabifr9mkqf4icrhvmi1c.apps.googleusercontent.com',
    iosClientId: '520533736138-0rk1vdqupdeoqo8cmho30ep3i8le1s9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIoKe9PbJOQyBNjYonemRg39trAYdNsX8',
    appId: '1:520533736138:ios:e4b4b87f38c619d0801233',
    messagingSenderId: '520533736138',
    projectId: 'android-main-activity',
    storageBucket: 'android-main-activity.firebasestorage.app',
    androidClientId: '520533736138-jen63e63sj6fabifr9mkqf4icrhvmi1c.apps.googleusercontent.com',
    iosClientId: '520533736138-0rk1vdqupdeoqo8cmho30ep3i8le1s9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterCloneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqZ_pZ8_y-4R0gpyQrR93XazG3jz0MF8w',
    appId: '1:520533736138:web:e7f1be81eb8942d6801233',
    messagingSenderId: '520533736138',
    projectId: 'android-main-activity',
    authDomain: 'android-main-activity.firebaseapp.com',
    storageBucket: 'android-main-activity.firebasestorage.app',
    measurementId: 'G-X9H1GJ1YK6',
  );
}
